---
sidebar: sidebar 
permalink: reference-new.html 
keywords: new features, release notes, enhancements 
summary: 包含多項新功能與增強功能的資訊。Cloud Volumes ONTAP 
---
= 更新功能Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
包含多項新功能與增強功能的資訊。Cloud Volumes ONTAP

最新版的BlueXP也會提供其他功能和增強功能。請參閱 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["BlueXP版本說明"^] 以取得詳細資料。



== 9.10.0 GA（2021年10月4日）

9.10.0 GA版本適用於AWS、Azure和Google Cloud。此版本包含下列新功能與增強功能。



=== 提升寫入效能

啟用高速寫入速度時、Cloud Volumes ONTAP 我們改善了寫入效能。



=== Azure中的NVRAM磁碟大小增加

對於Cloud Volumes ONTAP Azure中的全新功能、NVRAM磁碟大小從128 GiB增加至512 GiB。


NOTE: 如果您選擇單一節點系統、且虛擬機器支援Ultra SSD、則系統會使用32 GiB Ultra SSD來執行NVRAM、而非使用512 GiB Premium SSD。



== 所需版本的BlueXP Connector

BlueXP Connector必須執行3.9.11版或更新版本、才能部署新Cloud Volumes ONTAP 的版本號、並將現有系統升級至9.10.0版。



== 升級附註

* 必須從BlueXP完成升級。Cloud Volumes ONTAP您不應 Cloud Volumes ONTAP 使用 System Manager 或 CLI 來升級功能。這樣做可能會影響系統穩定性。
* 您可以從Cloud Volumes ONTAP 9.9.1版升級至E29 9.10.0。BlueXP會提示您將現有Cloud Volumes ONTAP 的版本更新為9.10.0。
+
http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["瞭解如何在BlueXP通知您時進行升級"^]。

* 單一節點系統的升級可讓系統離線長達25分鐘、在此期間I/O會中斷。
* 升級 HA 配對不中斷營運、而且 I/O 不中斷。在此不中斷營運的升級程序中、會同時升級每個節點、以繼續為用戶端提供 I/O 服務。
* 在 AWS 中、新的 Cloud Volumes ONTAP 部署不再支援 C4 、 M4 和 R4 EC2 執行個體類型。如果現有的系統執行於c4、m4或r4執行個體類型、則必須變更為c5、m5或R5執行個體系列中的執行個體類型。如果您無法變更執行個體類型、則必須在升級之前啟用增強的網路功能。
+
link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html#upgrades-in-aws-with-c4-m4-and-r4-ec2-instance-types["瞭解如何使用 C4 、 M4 和 R4 EC2 執行個體類型升級 AWS"^]。
link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["瞭解如何變更EC2執行個體類型Cloud Volumes ONTAP 以供使用"^]。

+
請參閱 link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["NetApp支援"^] 以深入瞭解這些執行個體類型的終止可用度和支援。





=== DS3_v2

從9.9.1版開始、DS3_v2 VM類型不再支援新的和現有Cloud Volumes ONTAP 的版本。如果此VM類型上有執行的現有系統、則在升級至9.10.0之前、必須先變更VM類型。
